'use strict';

// ISO standard time in GMT
const MAINTENANCE_START = '2019-04-19T00:00:00Z';
// downtime in minutes
const MAINTENANCE_TIME = 120;

// MAINTENANCE OPERATIONS
const MAINTENANCE_START_DATE = new Date(MAINTENANCE_START).getTime();
const MAINTENANCE_TIME_MS = (MAINTENANCE_TIME || 30) * 60 * 1000;

module.exports = {
  MAINTENANCE_START,
  MAINTENANCE_START_DATE,
  MAINTENANCE_TIME_MS,
};
